"use server";

import { generateExamContent, generateTopicSummary } from "@/lib/gemini";
import { ExamContent, TopicSummary } from "./types";

export async function getTopicInfo(topic: string): Promise<TopicSummary | null> {
  try {
    if (!topic || topic.trim().length < 2) {
      throw new Error("Topic name is too short");
    }
    return await generateTopicSummary(topic);
  } catch (error: any) {
    console.error("getTopicInfo Error:", error.message);
    if (error.message === "API_RATE_LIMIT") {
      return {
        topic: "API Rate Limit Reached",
        summary: "I've reached my daily limit! Please try again in a few minutes.",
        detailedExplanation: "API limit reached.",
        keyPoints: [],
        youtubeLinks: []
      };
    }
    return null;
  }
}

export async function processText(
  text: string,
  currentQuestions: any[] = [],
  currentMcqs: any[] = []
): Promise<ExamContent> {
  try {
    console.log("Processing text of length:", text.length);
    console.log("Text preview:", text.substring(0, 100) + "...");

    if (!text || text.trim().length < 10) {
      throw new Error("The PDF seems to be empty. Please try another file.");
    }

    // Split into larger chunks to reduce round trips and avoid timeouts
    const chunks = splitText(text, 12000); 

    let allQuestions: any[] = [...currentQuestions];
    let allMcqs: any[] = [...currentMcqs];

    // Limit to processing max 3 chunks to prevent server action timeout (ERR_ABORTED)
    const limitedChunks = chunks.slice(0, 3);
    console.log("CHUNKS TO PROCESS:", limitedChunks.length);

    // Process chunks in parallel for speed, but handle errors individually
    const results = await Promise.allSettled(
      limitedChunks.map(chunk => generateExamContent(chunk))
    );

    for (const result of results) {
      if (result.status === "fulfilled" && result.value) {
        console.log("Chunk result summary:", result.value.importantQuestions?.length, "questions,", result.value.mcqs?.length, "MCQs");
        allQuestions = mergeUnique(allQuestions, result.value.importantQuestions);
        allMcqs = mergeUnique(allMcqs, result.value.mcqs);
      } else if (result.status === "rejected") {
        const error = result.reason;
        if (error.message === "API_RATE_LIMIT") {
          throw error;
        }
        console.error("Error processing chunk with AI:", error.message);
      }
    }

    console.log("Final stats:", allQuestions.length, "questions,", allMcqs.length, "MCQs");

    // If still empty, return some placeholder data to avoid error
    if (allQuestions.length === 0 && allMcqs.length === 0) {
      console.warn("No questions generated by AI. Returning placeholders.");
      return {
        importantQuestions: [
          { question: "Summary of provided content", answer: `The AI processed ${text.length} characters of text but couldn't generate specific questions. The text begins with: "${text.substring(0, 200)}..."` },
          { question: "How to get better results?", answer: "Try uploading a clearer PDF or a higher resolution photo of your notes. Digital text works better than messy handwriting." }
        ],
        mcqs: []
      };
    }

    return {
      importantQuestions: allQuestions.slice(0, 15),
      mcqs: allMcqs.slice(0, 15),
    };

  } catch (error: any) {
    console.error("Server Action Error:", error.message);

    if (error.message === "API_RATE_LIMIT") {
      return {
        importantQuestions: [{ question: "API Rate Limit Reached", answer: "I've been working a bit too hard! Please wait a minute and try again." }],
        mcqs: [],
      };
    }

    // Generic fallback for any other error
    return {
      importantQuestions: [
        { question: "Processing Error", answer: "I encountered an error while analyzing your notes. This usually happens with very large files or messy scans." },
        { question: "Extracted Text Preview", answer: text?.substring(0, 500) || "No text could be extracted." }
      ],
      mcqs: [],
    };
  }
}

// Split text
function splitText(text: string, size: number) {
  const chunks = [];
  for (let i = 0; i < text.length; i += size) {
    chunks.push(text.slice(i, i + size));
  }
  return chunks;
}

// Remove duplicates
function mergeUnique(existing: any[], incoming: any[]) {
  const seen = new Set(existing.map((q) => q.question));

  for (const item of incoming || []) {
    if (!seen.has(item.question)) {
      existing.push(item);
      seen.add(item.question);
    }
  }

  return existing;
}
