"use client";

import { useState } from "react";
import { CheckCircle2, Circle, GraduationCap, ListChecks, Lightbulb, ArrowLeft } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { formatAnswer } from "@/lib/format";

interface ResultsDisplayProps {
  results: any;
  onBack?: () => void;
}

export function ResultsDisplay({ results, onBack }: ResultsDisplayProps) {
  console.log("ResultsDisplay RENDER WITH:", results);
  const [activeTab, setActiveTab] = useState<"questions" | "mcqs">("questions");
  const [showAnswers, setShowAnswers] = useState<{ [key: string]: boolean }>({});
  const [selectedMcqOptions, setSelectedMcqOptions] = useState<{ [key: number]: string }>({});

  const toggleAnswer = (idx: number) => {
    setShowAnswers((prev) => ({
      ...prev,
      [idx]: !prev[idx],
    }));
  };

  const handleMcqSelect = (idx: number, option: string) => {
    setSelectedMcqOptions((prev) => ({
      ...prev,
      [idx]: option,
    }));
  };

  // 🔥 Handle different possible API structures
  const importantQuestions =
    results?.importantQuestions ||
    results?.questions ||
    [];

  const mcqs =
    results?.mcqs ||
    results?.mcq ||
    [];

  // 🔥 Debug (you can remove later)
  console.log("RESULTS:", results);

  if (!results) {
    return (
      <div className="text-center py-10 text-gray-500">
        No data received
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-12 px-4">

      {/* 🔹 Tabs */}
      <div className="flex justify-center mb-12">
        <div className="p-1.5 rounded-[2rem] glass-card flex gap-1.5 shadow-lg border border-border">
          <button
            onClick={() => setActiveTab("questions")}
            className={`px-10 py-4 rounded-2xl text-base font-black flex items-center gap-3 transition-all ${
              activeTab === "questions"
                ? "bg-primary text-primary-foreground shadow-md"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <GraduationCap size={22} />
            <span>Questions</span>
          </button>

          <button
            onClick={() => setActiveTab("mcqs")}
            className={`px-10 py-4 rounded-2xl text-base font-black flex items-center gap-3 transition-all ${
              activeTab === "mcqs"
                ? "bg-primary text-primary-foreground shadow-md"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <ListChecks size={22} />
            <span>MCQs</span>
          </button>
        </div>
      </div>

      {/* 🔹 Action Buttons */}
      <div className="flex flex-col sm:flex-row justify-center items-center gap-4 mb-12">
        {onBack && (
          <button
            onClick={onBack}
            className="w-full sm:w-auto px-8 py-4 bg-background text-muted-foreground rounded-2xl font-bold flex items-center justify-center gap-3 shadow-sm border border-border transition-all hover:bg-muted active:scale-95"
          >
            <ArrowLeft size={20} />
            <span>Go Back</span>
          </button>
        )}
        <button
          onClick={() => {
            const printContent = `
              <html>
                <head>
                  <title>My Study Guide - Exam Buddy</title>
                  <style>
                    body { font-family: system-ui, -apple-system, sans-serif; color: #334155; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; background: #fdfdfd; }
                    h1 { color: #312e81; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px; font-weight: 900; }
                    h2 { color: #4338ca; margin-top: 30px; border-left: 4px solid #a5b4fc; padding-left: 15px; font-weight: 800; }
                    .card { background: #ffffff; border: 1px solid #f1f5f9; border-radius: 16px; padding: 24px; margin-bottom: 24px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); }
                    .question { font-weight: 900; color: #1e293b; margin-bottom: 12px; font-size: 1.2em; }
                    .answer { color: #475569; font-weight: 500; }
                    .mcq-option { margin-left: 20px; color: #64748b; font-weight: 600; margin-bottom: 4px; }
                    .footer { margin-top: 60px; text-align: center; color: #94a3b8; font-size: 0.8em; font-weight: 600; }
                  </style>
                </head>
                <body>
                  <h1>My Personal Study Guide</h1>
                  <p>Generated by your Exam Buddy AI on ${new Date().toLocaleDateString()}</p>

                  ${importantQuestions.length > 0 ? `
                    <h2>Important Questions & Answers</h2>
                    ${importantQuestions.map((q: any, i: number) => `
                      <div class="card">
                        <div class="question">${i + 1}. ${q.question || q.q}</div>
                        <div class="answer">${formatAnswer(q.answer || q.a)}</div>
                      </div>
                    `).join("")}
                  ` : ""}

                  ${mcqs.length > 0 ? `
                    <h2>Practice MCQs</h2>
                    ${mcqs.map((m: any, i: number) => `
                      <div class="card">
                        <div class="question">${i + 1}. ${m.question || m.q}</div>
                        ${(m.options || m.choices || []).map((opt: string) => `<div class="mcq-option">• ${opt}</div>`).join("")}
                        <div class="answer" style="margin-top:12px; font-weight:900; color:#4338ca;">Correct Answer: ${m.answer || m.a}</div>
                      </div>
                    `).join("")}
                  ` : ""}

                  <div class="footer">Built with ❤️ by Exam Buddy</div>
                </body>
              </html>
            `;

            const w = window.open("", "_blank");
            if (w) {
              w.document.write(printContent);
              w.document.close();
              w.print();
            }
          }}
          className="w-full sm:w-auto px-8 py-4 bg-primary text-primary-foreground rounded-2xl font-black flex items-center justify-center gap-3 shadow-xl shadow-primary/20 transition-all hover:scale-105 active:scale-95"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
          <span>Save as PDF / Print</span>
        </button>
      </div>

      {/* 🔹 Content */}
      <div className="max-w-3xl mx-auto space-y-8">

        {/* QUESTIONS */}
        {activeTab === "questions" &&
          (importantQuestions.length > 0 ? (
            importantQuestions.map((q: any, idx: number) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="group p-8 glass-card rounded-[2.5rem] shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-500 border border-border"
              >
                <div className="flex flex-col gap-5">
                  <div className="flex items-start justify-between gap-5">
                    <span className="flex-shrink-0 w-12 h-12 rounded-2xl bg-primary text-primary-foreground flex items-center justify-center font-black text-xl shadow-lg shadow-primary/20">
                      {idx + 1}
                    </span>
                    <h3 className="flex-1 font-black text-2xl text-foreground leading-tight pt-1 tracking-tight">
                      {q.question || q.q || "No Question"}
                    </h3>
                  </div>
                  
                  <button
                    onClick={() => toggleAnswer(idx)}
                    className={`self-start px-8 py-3 rounded-xl font-black text-sm uppercase tracking-widest transition-all ${
                      showAnswers[idx] 
                        ? "bg-muted text-muted-foreground" 
                        : "bg-primary text-primary-foreground hover:opacity-90 shadow-md shadow-primary/20"
                    }`}
                  >
                    {showAnswers[idx] ? "Hide Answer" : "Reveal Answer"}
                  </button>
                </div>

                <AnimatePresence>
                  {showAnswers[idx] && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="mt-8 p-8 rounded-[2rem] bg-secondary/30 border border-secondary/20">
                        <div
                          className="text-foreground leading-relaxed text-lg font-medium opacity-90"
                          dangerouslySetInnerHTML={{
                            __html: formatAnswer(q.answer || q.a || "No Answer"),
                          }}
                        />
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))
          ) : (
            <div className="text-center py-20 glass-card rounded-[3rem] border-2 border-dashed border-border">
              <p className="text-muted-foreground font-bold uppercase tracking-widest text-sm">No questions found. Try another file!</p>
            </div>
          ))}

        {/* MCQs */}
        {activeTab === "mcqs" &&
          (mcqs.length > 0 ? (
            mcqs.map((m: any, idx: number) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="p-8 glass-card rounded-[2.5rem] shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-500 border border-border"
              >
                <div className="flex items-start gap-5 mb-10">
                  <span className="flex-shrink-0 w-12 h-12 rounded-2xl bg-accent text-accent-foreground flex items-center justify-center font-black text-xl shadow-lg shadow-accent/20">
                    {idx + 1}
                  </span>
                  <h3 className="font-black text-2xl text-foreground leading-tight pt-1 tracking-tight">
                    {m.question || m.q || "No Question"}
                  </h3>
                </div>

                <div className="grid gap-4">
                  {(m.options || m.choices || []).map((opt: string, i: number) => {
                    const isSelected = selectedMcqOptions[idx] === opt;
                    const isCorrect = opt === (m.answer || m.a);
                    const showFeedback = selectedMcqOptions[idx] !== undefined;

                    let bgClass = "bg-muted/50 border-border hover:border-primary/50 text-foreground";
                    if (showFeedback) {
                      if (isCorrect) {
                        bgClass = "bg-green-500/10 border-green-500/50 text-green-700 dark:text-green-400 font-bold";
                      } else if (isSelected) {
                        bgClass = "bg-red-500/10 border-red-500/50 text-red-700 dark:text-red-400 font-bold";
                      }
                    } else if (isSelected) {
                      bgClass = "bg-primary/10 border-primary/50 text-primary-foreground font-bold";
                    }

                    return (
                      <button
                        key={i}
                        disabled={showFeedback}
                        onClick={() => handleMcqSelect(idx, opt)}
                        className={`group p-6 border rounded-2xl flex items-center justify-between text-left transition-all transform active:scale-[0.98] ${bgClass}`}
                      >
                        <span className="font-bold text-lg">{opt}</span>
                        
                        {showFeedback && (
                          isCorrect ? (
                            <CheckCircle2 size={24} className="shrink-0 text-green-500" />
                          ) : isSelected ? (
                            <Circle size={24} className="shrink-0 text-red-500" />
                          ) : null
                        )}
                      </button>
                    );
                  })}
                </div>
                
                <AnimatePresence>
                  {selectedMcqOptions[idx] && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="mt-8 p-8 rounded-[2rem] bg-primary text-primary-foreground shadow-xl shadow-primary/20"
                    >
                      <div className="flex items-center gap-4">
                        <Lightbulb className="text-primary-foreground shrink-0" size={24} />
                        <p className="font-medium">
                          <span className="font-black uppercase tracking-widest text-xs block mb-1 text-primary-foreground/80">Correct Answer</span>
                          <span className="text-xl font-black">{m.answer || m.a}</span>
                        </p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))
          ) : (
            <div className="text-center py-20 glass-card rounded-[3rem] border-2 border-dashed border-border">
               <p className="text-muted-foreground font-bold uppercase tracking-widest text-sm">No MCQs available. Try another file!</p>
             </div>
           ))}

       </div>
     </div>
   );
}